### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by ogonki-vetochki** [openx/ODS-Ruby-API-Client#1]
It used to work, but with no changes made it just stopped. The error I getting:

```
2.4.6 :013 >     open_x_helper = OX3APIClient.new(
2.4.6 :014 >           @credentials[:email],
2.4.6 :015 >           @credentials[:password],
2.4.6 :016 >           @credentials[:site_url],
2.4.6 :017 >           @credentials[:consumer_key],
2.4.6 :018 >           @credentials[:consumer_secret],
2.4.6 :019 >           @credentials[:realm])
TypeError: no implicit conversion of nil into String
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:203:in `unescape'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:203:in `block in parse_tokens'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:201:in `each'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:201:in `inject'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:201:in `parse_tokens'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:163:in `authorize_token'
	from /Users/ogonki-vetochki/code/ad-libertas-reports-client/app/helpers/open_x_helper.rb:28:in `initialize'
	from (irb):13:in `new'
	from (irb):13
	from /Users/ogonki-vetochki/.rvm/gems/ruby-2.4.6/gems/railties-4.2.11.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/ogonki-vetochki/.rvm/gems/ruby-2.4.6/gems/railties-4.2.11.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/ogonki-vetochki/.rvm/gems/ruby-2.4.6/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ogonki-vetochki/.rvm/gems/ruby-2.4.6/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ogonki-vetochki/.rvm/gems/ruby-2.4.6/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by maslosky** [comment]
In such cases please always file a ticket with OpenX Support. This might be caused by something not-related to this library.
